// packages/react/src/components/validation-summary.tsx
import type { HTMLAttributes } from 'react';
import type { ValidationResult } from '@validation-rules/core';
import { fieldId } from '../utilities/paths';

export interface ValidationSummaryProps extends Omit<HTMLAttributes<HTMLElement>, 'children'> {
  errors: readonly ValidationResult[];
  heading?: string;
  linkErrors?: boolean;
}

export function ValidationSummary({
  errors,
  heading = 'Please correct the following errors',
  linkErrors = true,
  ...props
}: ValidationSummaryProps) {
  if (errors.length === 0) return null;
  return (
    <section {...props} role="alert" aria-labelledby="validation-summary-heading">
      <h2 id="validation-summary-heading">{heading}</h2>
      <ul>
        {errors.map(({ propertyName, error }, index) => (
          <li key={`${propertyName}-${error.message}-${index}`}>
            {linkErrors ? <a href={`#${fieldId(propertyName)}`}>{error.message}</a> : error.message}
          </li>
        ))}
      </ul>
    </section>
  );
}

// projects/core/src/lib/components/validation-summary.component.ts
import { Component, Input } from '@angular/core';
import { ValidationResult } from '../interfaces/validation-result.interface';

@Component({
  selector: 'ngx-validation-summary',
  template: `
    <div *ngIf="errors.length" class="ngx-valid-summary" role="alert" [attr.aria-live]="'polite'">
      <strong class="ngx-valid-summary-title">{{ title }}</strong>
      <ul class="ngx-valid-summary-list">
        <li *ngFor="let err of errors">{{ err.error.message }}</li>
      </ul>
    </div>
  `
})
export class ValidationSummaryComponent {
  @Input() model: any;
  @Input() title = 'Please correct the following errors:';

  get errors(): ValidationResult[] {
    return this.model?.validationResults ?? [];
  }
}
